num1 = int(input("enter any number :"))
num2 = int(input("enter any number :"))
num3 = int(input("enter any number :"))
print(num1 + num2 + num3)
print(num1 - num2 - num3)
print(num1 / num2 / num3)
print(num1 * num2 * num3)
