surname = "Bandelidze"
print(surname[0])
print(surname[1])
print(surname[2])
print(surname[3])
print(surname[4])
print(surname[5])
print(surname[6])
print(surname[7])
print(surname[8])
print(surname[9])
